"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.n5 = exports.n4 = exports.n3 = exports.n2 = exports.n1 = void 0;
exports.n1 = 10;
exports.n2 = 20;
exports.n3 = 30;
exports.n4 = 40;
exports.n5 = 50;
const souDefault = "souDefaultString";
exports.default = souDefault;
